<?php
/**
 * @var $hotel
 * @var $imagenes
 * @var $habitaciones
 */
?>

<!DOCTYPE html>
<html lang="es-ES">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <title>Vista única</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-warning bg-opacity-50 sticky-top">
    <a class="navbar-brand ">
        <img src="../img/imagenhoteles.png" width="25">
    </a>
    <a class="navbar-brand " href="../Controlador/controladorPaginaPrincipal.php">Reserva el Top 10 hoteles</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ">

            <li class="nav-item active ">
                <a class="nav-link" href="#">Quienes somos </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contacto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Experiencia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="../controlador/listaHotel.php">Home</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        </form>
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </div>
</nav>
<h1>Apunto de reservar, un pasito más...</h1>

<?php foreach ($hotel as $hotelito) { ?>
    <div class="container">
        <div class="row">
        <div>

            <table>
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Zona</th>
                    <th>Ciudad</th>
                    <th>Puntuación</th>
                </tr>
                <tr>
                    <td>116</td>
                    <td>  <?php echo $hotelito->getDescripcion(); ?></td>
                    <td><?php echo $hotelito->getEstado(); ?></td>
                    <td><?php echo $hotelito->getZona(); ?></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>



        </div>
        </div>
<?php } ?>

        <div class="row">
<div class="multi-carousel vertical" style="max-width: 20rem;">

    <div class="multi-carousel-inner">
        <?php foreach ($imagenes

        as $imagen){ ?>
        <div class="multi-carousel-item">
            <img src="<?php echo $imagen->getUrl(); ?>" alt="Winter Landscape" class="max-width: 20rem;"/>
        </div>

    </div>
</div>
    <?php } ?>



</div>
</div>
</body>
</html>

