
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="../Styles/main.css" rel="stylesheet">
    <link href="../Styles/login.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Top 10 hoteles</title>
</head>
<body>
<h1>Login</h1>
<form method="post">
    Mail: <input type="text" name="mail"/>
    <br>
    Password: <input type="password" name="password"/>
    <br>
    <input type="submit" value="submit"/>
</form>
<span>No tienes cuenta? <a href="../Controlador/controladorSigUp.php">Create una cuenta</a></span>
</body>
</html>