<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="../Styles/main.css" rel="stylesheet">
    <link href="../Styles/login.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Top 10 hoteles</title>
</head>
<body>
<h1>Sign up</h1>
<form method="post">
    Mail: <input type="text" name="mail"/>
    <br>
    Password: <input type="password" name="password"/>
    <br>
    Repeat password: <input type="password" name="password2"/>
    <br>
    Teléfono: <input type="number" name="telefono"/>
    <br>
    NickName: <input type="text" name="name"/>
    <br>
    <input type="submit" value="submit"/>
</form>
<span>Ya tienes cuenta? Entra<a href="../Controlador/controladorLogin.php">Login</a></span>
<!-- AQUÍ PODEMOS CERRAR EL LOGIN-->
<span>Quieres salir? <a href="../Controlador/controladorLogout.php">Logout</a></span>
</body>
</html>