
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>


<body>
<?php foreach ($property as $properties){ ?>
<table>
    <th><?php $properties->getBathrooms(); ?></th>
    <th>cabeza2</th>
    <tr>titul</tr>
    <tr>titul2</tr>
</table>
<?php } ?>
</body>

</html>