<?php
/**
 * @var $jugador
 * @var $usuario
 * @var $ciudades
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>World Game</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
<h1>Countries</h1>
<br>
<h2>My countries</h2>
<table>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Population</th>
        <th>GNP</th>
        <th>NumLanguages</th>
        <th>NumCities</th>
        <th>Owner</th>
    </tr>
    <?php foreach ( $jugador as $tabla){ ?>
    <tr>
        <td><?php echo $tabla->getCode(); ?></td>
        <td><?php echo $tabla->getName(); ?></td>
        <td><?php echo $tabla->getPopulation(); ?></td>
        <td><?php echo $tabla->getGNP() ?></td>
        <td><?php echo $tabla->getCapital(); ?></td>
        <td><?php echo $tabla->getUserId()->getId(); ?></td>
        <td><a href="#"></a><?php echo $tabla->getUserId()->getMail(); ?></td>
    </tr>
        <?php $fuerza = $fuerza + $tabla->getPopulation() + $tabla->getGNP();
        //$fuerza = number_format($fuerza,0,0,0)?>
    <?php } ?>
    <h2><?php echo"Fuerza total del ususario: ".$fuerza."</h2>"; ?>
</table>
<br>
<h2>Other countries</h2>
<table>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Population</th>
        <th>GNP</th>
        <th>NumLanguages</th>
        <th>NumCities</th>
        <th>Owner</th>
        <th>Action</th>
    </tr>
<?php foreach ($ciudades as $city) { ?>
    <tr>
        <td><?php echo $city->getCode(); ?></td>
        <td><?php echo $city->getName(); ?></td>
        <td><?php echo $city->getPopulation(); ?></td>
        <td><?php echo $city->getGNP(); ?></td>
        <td><?php echo $city->getCapital(); ?></td>
        <td><?php  echo $city->getUserId()->getId(); ?></td>
        <td><b><?php echo $city->getUserId()->getMail(); ?></b></td>
        <?php $fuerzaPais =  $city->getPopulation() + $city->getGNP(); ?>
        <td><a href="../CONTROLADOR/controladorAtaque.php?Code=<?php echo $city->getCode() . "&FuerzaPais=".$fuerzaPais."&FuerzaUsuario=".$fuerza; ?>">Attack</a></td>
    </tr>
   <?php } ?>
    <a href="../CONTROLADOR/controladorLogout.php">Logout</a>
</table>
</body>
</html>
