<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>World Game</title>
</head>
<body>
<h1>Sign up</h1>
<form method="post">
    Mail: <input type="text" name="mail"/>
    <br>
    Password: <input type="password" name="password"/>
    <br>
    Repeat password: <input type="password" name="password2"/>
    <br>
    <input type="submit" value="submit"/>
</form>
<span>Already have an account? <a href="../CONTROLADOR/controladorLogin.php">Login</a></span>
</body>
</html>