
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>World Game</title>
</head>
<body>
<h1>Login</h1>
<form method="post">
    Mail: <input type="text" name="mail"/>
    <br>
    Password: <input type="password" name="password"/>
    <br>
    <input type="submit" value="submit"/>
</form>
<span>Don't have an account? <a href="../CONTROLADOR/controladorRegistro.php">Create account</a></span>
</body>
</html>